# Generated by Django 5.2 on 2025-04-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodId', models.CharField(max_length=100)),
                ('Items', models.CharField(max_length=250)),
                ('Price', models.IntegerField(max_length=250)),
                ('Quantity', models.IntegerField(max_length=250)),
                ('Total', models.IntegerField(max_length=250)),
            ],
        ),
    ]
