# Generated by Django 5.2 on 2025-04-15 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='fooditems',
            name='Items',
        ),
        migrations.RemoveField(
            model_name='fooditems',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='fooditems',
            name='Quantity',
        ),
        migrations.RemoveField(
            model_name='fooditems',
            name='Total',
        ),
        migrations.RemoveField(
            model_name='fooditems',
            name='foodId',
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.fooditem')),
            ],
        ),
    ]
