# Generated by Django 5.2 on 2025-04-15 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_fooditem_remove_fooditems_items_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodItems',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='image',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='food_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='myapp.fooditem'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
