# Generated by Django 5.2 on 2025-04-24 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_login_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
